local map = vim.keymap.set

map({"n", "v"}, "<Space>", "10j")
map({"n", "v"}, "<Backspace>", "10k")
map("n", "<C-H>", "<C-W>h")
map("n", "<C-J>", "<C-W>j")
map("n", "<C-K>", "<C-W>k")
map("n", "<C-L>", "<C-W>l")
map("n", "<C-N>", "<Cmd>bnext<CR>")
map("n", "<C-P>", "<Cmd>bprevious<CR>")
map("n", "<Leader>\\", ":nohlsearch<CR>")
-- map("x", "\"'", "<Esc>`>a'<Esc>`<i'<Esc>", { remap = false })
-- map("x", "\"\"", "<Esc>`>a\"<Esc>`<i\"<Esc>", { remap = false })
-- map("x", "\"(", "<Esc>`>a)<Esc>`<i(<Esc>", { remap = false })
-- map("x", "\"[", "<Esc>`>a]<Esc>`<i[<Esc>", { remap = false })
-- map("x", "\"{", "<Esc>`>a}<Esc>`<i{<Esc>", { remap = false })
-- map("x", "\"<Space>", "<Esc>`>a<Space><Esc>`<i<Space><Esc>", { remap = false })
